export const UPDATE_DISPLAYED_QUESTIONS_INITIALIZE =
  "UPDATE_DISPLAYED_QUESTIONS_INITIALIZE";
export const UPDATE_DISPLAYED_QUESTIONS_SUCCESS =
  "UPDATE_DISPLAYED_QUESTIONS_SUCCESS";
export const UPDATE_DISPLAYED_QUESTIONS_FAIL =
  "UPDATE_DISPLAYED_QUESTIONS_FAIL";

export const UPDATE_ALL_QUESTIONS_INITIALIZE =
  "UPDATE_ALL_QUESTIONS_INITIALIZE";
export const UPDATE_ALL_QUESTIONS_SUCCESS = "UPDATE_ALL_QUESTIONS_SUCCESS";
export const UPDATE_ALL_QUESTIONS_FAIL = "UPDATE_ALL_QUESTIONS_FAIL";

export const ADD_QUESTIONS_TO_DOCUMENT_INITIALIZE =
  "ADD_QUESTIONS_TO_DOCUMENT_INITIALIZE";
export const ADD_QUESTIONS_TO_DOCUMENT_SUCCESS =
  "ADD_QUESTIONS_TO_DOCUMENT_SUCCESS";
export const ADD_QUESTIONS_TO_DOCUMENT_FAIL = "ADD_QUESTIONS_TO_DOCUMENT_FAIL";

export const UPDATE_DOCUMENT_QUESTIONS_INITIALIZE =
  "UPDATE_DOCUMENT_QUESTIONS_INITIALIZE";
export const UPDATE_DOCUMENT_QUESTIONS_SUCCESS =
  "UPDATE_DOCUMENT_QUESTIONS_SUCCESS";
export const UPDATE_DOCUMENT_QUESTIONS_FAIL = "UPDATE_DOCUMENT_QUESTIONS_FAIL";

export const CREATE_DOCUMENT_INITIALIZE = "CREATE_DOCUMENT_INITIALIZE";
export const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS";
export const CREATE_DOCUMENT_FAIL = "CREATE_DOCUMENT_FAIL";

export const LOGIN_INITIALIZE = "LOGIN_INITIALIZE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_INITIALIZE = "REGISTER_INITIALIZE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
