export const UPDATE_DISPLAYED_QUESTIONS_INITIALIZE =
  "UPDATE_DISPLAYED_QUESTIONS_INITIALIZE";
export const UPDATE_DISPLAYED_QUESTIONS_SUCCESS =
  "UPDATE_DISPLAYED_QUESTIONS_SUCCESS";
export const UPDATE_DISPLAYED_QUESTIONS_FAIL =
  "UPDATE_DISPLAYED_QUESTIONS_FAIL";

export const UPDATE_ALL_QUESTIONS_INITIALIZE =
  "UPDATE_ALL_QUESTIONS_INITIALIZE";
export const UPDATE_ALL_QUESTIONS_SUCCESS = "UPDATE_ALL_QUESTIONS_SUCCESS";
export const UPDATE_ALL_QUESTIONS_FAIL = "UPDATE_ALL_QUESTIONS_FAIL";

export const ADD_QUESTIONS_TO_DOCUMENT_INITIALIZE =
  "ADD_QUESTIONS_TO_DOCUMENT_INITIALIZE";
export const ADD_QUESTIONS_TO_DOCUMENT_SUCCESS =
  "ADD_QUESTIONS_TO_DOCUMENT_SUCCESS";
export const ADD_QUESTIONS_TO_DOCUMENT_FAIL = "ADD_QUESTIONS_TO_DOCUMENT_FAIL";

export const UPDATE_DOCUMENT_QUESTIONS_INITIALIZE =
  "UPDATE_DOCUMENT_QUESTIONS_INITIALIZE";
export const UPDATE_DOCUMENT_QUESTIONS_SUCCESS =
  "UPDATE_DOCUMENT_QUESTIONS_SUCCESS";
export const UPDATE_DOCUMENT_QUESTIONS_FAIL = "UPDATE_DOCUMENT_QUESTIONS_FAIL";
