export const ADD_QUESTION_INITIALIZE = "ADD_QUESTION_INITIALIZE";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL";

export const UPDATE_DISPLAYED_QUESTIONS_INITIALIZE =
  "UPDATE_DISPLAYED_QUESTIONS_INITIALIZE";
export const UPDATE_DISPLAYED_QUESTIONS_SUCCESS =
  "UPDATE_DISPLAYED_QUESTIONS_SUCCESS";
export const UPDATE_DISPLAYED_QUESTIONS_FAIL =
  "UPDATE_DISPLAYED_QUESTIONS_FAIL";

export const UPDATE_ALL_QUESTIONS_INITIALIZE =
  "UPDATE_ALL_QUESTIONS_INITIALIZE";
export const UPDATE_ALL_QUESTIONS_SUCCESS = "UPDATE_ALL_QUESTIONS_SUCCESS";
export const UPDATE_ALL_QUESTIONS_FAIL = "UPDATE_ALL_QUESTIONS_FAIL";
